name: Vault Examples Tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    env:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: testtoken
      EXPECTED_SECRET_VALUE: Hashi123
    steps:
    - uses: actions/checkout@v2

    - name: Start Vault server
      run: |
        mkdir $HOME/vault-bin
        wget https://releases.hashicorp.com/vault/1.8.3/vault_1.8.3_linux_amd64.zip -O "vault.zip" -P $HOME/vault-bin /
        unzip $HOME/vault.zip
        echo "$HOME/vault-bin" >> $GITHUB_PATH
        vault server -dev

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.5'

    - name: Set up environment
      run: |
        ./setup.sh
        echo "APPROLE_ROLE_ID=$(curl -H "X-Vault-Token: ${VAULT_DEV_ROOT_TOKEN_ID}" ${VAULT_ADDR}/v1/auth/approle/role/my-role/role-id | jq -r .data.role_id)" >> $GITHUB_ENV

    - name: Run tests
      run: |
        cd go
        TOKEN=${VAULT_DEV_ROOT_TOKEN_ID} go test -count=1
